# Documentation
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'monthly'
#   - package-ecosystem: 'npm'
#     directory: '/'
#     schedule:
#       interval: 'weekly'
#
#   - package-ecosystem: 'npm'
#     directory: '/bids-validator-web'
#     schedule:
#       interval: 'weekly'
