variables:
  GIT_STRATEGY: fetch
  GIT_CHECKOUT: "false"
  GIT_SUBMODULE_STRATEGY: normal
  NODE_OPTIONS: --no-warnings
stages:
  - test

tests:
  stage: test
  tags:
    - windows
  before_script:
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - choco install -y npm
    - refreshenv
  script:
    - git config core.symlinks true
    - git checkout $CI_COMMIT_REF_NAME
    - git submodule update --init --depth 1
    - npm install
    - npm run test -- --testTimeout 30000
