name: Python tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Set git name/email
        run: |
          git config --global user.email "bids.maintenance@gmail.com"
          git config --global user.name "bids-maintenance"
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Install git-annex ubuntu
        if: matrix.platform == 'ubuntu-latest'
        shell: bash -l {0}
        run: conda install -c conda-forge git-annex

      - name: Install git-annex macos
        if: matrix.platform == 'macos-latest'
        shell: bash -l {0}
        run: brew install git-annex

      - name: Install git-annex windows
        if: matrix.platform == 'windows-latest'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install git-annex --yes --ignore-checksums

      - name: Install remaining dependencies
        shell: bash -l {0}
        run: |
          which python
          pip install datalad
          pip install pytest pytest-sugar flake8 pydocstyle
          pip install -e ./bids-validator

      - name: Check formatting
        shell: bash -l {0}
        run: |
          cd bids-validator
          flake8 bids_validator
          pydocstyle bids_validator/bids_validator.py
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          cd bids-validator
          pytest --doctest-modules bids_validator --verbose
